/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import Funciones.Encriptar;
import Funciones.lecturayesc;
import Inicio.inicio_sesion;
import Principal.Principal_administrador;
import Principal.Principal_empleado;
import com.sun.awt.AWTUtilities;
import facturacion.Ventas;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import splash.FadeEffect;





/**
 *
 * @author Chappie
 */
public class IniciarSesion extends javax.swing.JFrame {

    Connection conexion;
    Encriptar encriptar=new Encriptar();
    AudioClip iniciar;
    
    String nombre_u;
    String contra_u;
    String tipo;
     lecturayesc lec=new lecturayesc();
    private List<personal> listadoPersonal;
    ArrayList <personal> busquedaPersonal = new ArrayList<>();
    PreparedStatement buscar;
    
    public IniciarSesion(Connection conexion) {
        initComponents();
        setLocationRelativeTo(null); //Centra la vantana en la pantalla
        //
        Shape forma = new RoundRectangle2D.Double(0, 0, getBounds().width, getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);
       
        //news
        //tran();
        this.conexion = conexion;
        this.setLocationRelativeTo(null);
        this.txfUsuario.requestFocus();
        FadeEffect.fadeInFrame(this, 50, 0.1f);
        setLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txfUsuario = new javax.swing.JTextField();
        txfContraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 46)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estetica Lis");

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 610));

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Iniciar Sesión");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 275, 53));

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONTRASEÑA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(73, 181, 172));
        btnIngresar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setFocusPainted(false);
        btnIngresar.setFocusable(false);
        btnIngresar.setRequestFocusEnabled(false);
        btnIngresar.setVerifyInputWhenFocusTarget(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 210, 60));

        txfUsuario.setBackground(new java.awt.Color(102, 0, 204));
        txfUsuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txfUsuario.setForeground(new java.awt.Color(73, 181, 172));
        txfUsuario.setBorder(null);
        txfUsuario.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel2.add(txfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 40));

        txfContraseña.setBackground(new java.awt.Color(102, 0, 204));
        txfContraseña.setFont(txfContraseña.getFont().deriveFont(txfContraseña.getFont().getSize()+7f));
        txfContraseña.setForeground(new java.awt.Color(73, 181, 172));
        txfContraseña.setBorder(null);
        txfContraseña.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel2.add(txfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 270, 36));

        jSeparator1.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator1.setForeground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 310, 10));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator2.setForeground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 310, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/userLog.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 40, 36));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Lock_25px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 40, 42));

        jCheckBox1.setBackground(new java.awt.Color(102, 0, 204));
        jCheckBox1.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Recuérdame");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, -1));

        jLabel9.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 181, 172));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("x");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        System.out.println( "Hola "+encriptar.codificar(encriptar.getLlave_n(), "admi"));       

        entrar(); 
    }//GEN-LAST:event_btnIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPasswordField txfContraseña;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables

    public void entrar() {
        lec.rutas();//aqui generamos las rutas
        ArrayList<String> VerificarUsuario = new ArrayList<>();
        ArrayList<String> Verificarcontra = new ArrayList<>();
        PreparedStatement buscarUsuario;
        try {
            buscarUsuario = conexion.prepareStatement("SELECT *FROM usuario WHERE nombreUsuario=? AND contraseña=? ");
            buscarUsuario.setString(1, txfUsuario.getText());
            buscarUsuario.setString(2, encriptar.codificar(encriptar.getLlave_n(), txfContraseña.getText()));
            buscarUsuario.execute();
            ResultSet resultadosObtenidos = buscarUsuario.executeQuery();
            String CUIclie = "";
            while (resultadosObtenidos.next()) {
                nombre_u = resultadosObtenidos.getString("nombreUsuario");
                contra_u = resultadosObtenidos.getString("contraseña");
                tipo = resultadosObtenidos.getString("tipoUsuario_id");
                CUIclie = resultadosObtenidos.getString("empleado_id");
                Ventas.idusuarios(CUIclie);
                consultar(tipo);

                for (int i = 0; i < busquedaPersonal.size(); i++) {

                    if (Integer.valueOf(tipo) == Integer.valueOf(busquedaPersonal.get(i).getId())) {
                        System.out.println("econtrado");
                        String nue = busquedaPersonal.get(i).getTipo();
                        if (busquedaPersonal.get(i).getTipo().equals("a")) {
                            ver = true;
                            empleado = false;

                        } else if (busquedaPersonal.get(i).getTipo().equals("b")) {
                            empleado = true;
                            ver = false;

                        }

                    }
                    System.out.println(busquedaPersonal.get(i).getId());

                }

                String real = encriptar.decodificar(encriptar.getLlave_n(), contra_u);
                System.out.println(real);
                VerificarUsuario.add(contra_u);
                Verificarcontra.add(contra_u);
            }

            if (VerificarUsuario.isEmpty() && Verificarcontra.isEmpty()) { //si mi lista esta vacia no hay ningun usuario
                JOptionPane.showMessageDialog(this, "Usuario y/o Contraseña Incorrecta");

            } else {
                iniciar = java.applet.Applet.newAudioClip(getClass().getResource("/sonidos/sonido.wav"));
                iniciar.play();
                System.out.println(ver);
                if (ver == true) {
                    System.out.println("Bienevido administrador");
                    Principal_administrador ventanaAdm = new Principal_administrador();
                    ventanaAdm.setVisible(true);
                    this.dispose();;
                } else if (empleado == true) {
                    Principal_empleado ventanaempleados = new Principal_empleado();
                    ventanaempleados.setVisible(true);
                    this.dispose();
                }
                
                lec.insertaraux(nombre_u);
                    
            }

        } catch (SQLException ex) {
            Logger.getLogger(inicio_sesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(inicio_sesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setLogo(){
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/imagenes/logotipo.png"));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(lbllogo.getWidth(),
                lbllogo.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        lbllogo.setIcon(iconoEscalado);
    }
    
    public void consultar (String valor) throws SQLException, IOException{
        
        buscar = conexion.prepareStatement("SELECT *FROM tipousuario WHERE id LIKE ?");
               
        buscar.setString(1, valor);
        buscar.execute();

        ResultSet resultadosObtenidos=buscar.executeQuery();
        while(resultadosObtenidos.next()){
            String id =  resultadosObtenidos.getString("id");
            String ad= resultadosObtenidos.getString("tipo") ;
       
            //Crea un objeto de tipo estudiante en base a la tupla que acaba de leer
                personal personaln= new personal(id,ad);
                //Añade ese estudiante a un listado para mostrar los datos luego en una tabla
                busquedaPersonal.add(personaln);
        }
        
    }
     Boolean ver=false;
     Boolean empleado=false;
}
