/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servicios;

import empleados.*;
import com.github.sarxos.webcam.Webcam;
import conexion.Conectando;


import java.awt.Color;

import java.awt.Image;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import productos.Insercion;

import rojerusan.RSNotifyAnimated;


/**
 *
 * @author enrique7cp@gmail.com
 */
public class insertarser extends javax.swing.JDialog {

    Conectando con = new Conectando();
    Connection nConect;
    listarservicios lis=new listarservicios();

    /**
     * Creates new form Insercion
     */
        
    public insertarser() {
        //super(parent, modal);
        this.nConect = con.conect();
        initComponents();
        this.setLocationRelativeTo(null);
        lis.listar("");
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCerrar1 = new javax.swing.JLabel();
        lbtitulo = new javax.swing.JLabel();
        combcat = new javax.swing.JComboBox<String>();
        btnregistrar = new javax.swing.JButton();
        jprecio = new javax.swing.JSpinner();
        jlimpiar = new javax.swing.JToggleButton();
        lblnombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblId.setText("ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar1.setBackground(new java.awt.Color(102, 0, 204));
        lblCerrar1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCerrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar1.setText("x");
        lblCerrar1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCerrar1.setOpaque(true);
        lblCerrar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseMoved(evt);
            }
        });
        lblCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseExited(evt);
            }
        });
        jPanel1.add(lblCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 30, 30));

        lbtitulo.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitulo.setText("REGISTRAR");
        jPanel1.add(lbtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 252, 38));

        combcat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combcat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Mujer ", "Hombre", "Niño ", "Niña" }));
        combcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combcatActionPerformed(evt);
            }
        });
        jPanel1.add(combcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 120, -1));

        btnregistrar.setText("REGISTRAR");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jprecio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jprecio.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel1.add(jprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 40));

        jlimpiar.setText("Limpiar");
        jlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        lblnombre.setBackground(new java.awt.Color(51, 51, 255));
        lblnombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setBorder(null);
        lblnombre.setCaretColor(new java.awt.Color(255, 255, 255));
        lblnombre.setOpaque(false);
        lblnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblnombreKeyTyped(evt);
            }
        });
        jPanel1.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Precio:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblId1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblId1.setText("ID");
        jPanel1.add(lblId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 20, 40));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Nombre:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Categoria:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void lblCerrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseExited
        lblCerrar1.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_lblCerrar1MouseExited

    private void lblCerrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCerrar1MouseEntered

    private void lblCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCerrar1MouseClicked

    private void lblCerrar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseMoved
        lblCerrar1.setBackground(Color.RED);
    }//GEN-LAST:event_lblCerrar1MouseMoved

    private void combcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combcatActionPerformed
      

    }//GEN-LAST:event_combcatActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed

        
        if (lblnombre.equals("") || combcat.getSelectedIndex() == 0
                || ((Integer)jprecio.getValue()==0)
                ) {
            JOptionPane.showMessageDialog(null, "FALTAN LLENAR CAMPOS");
        } else {

             if (this.btnregistrar.getText().equals("REGISTRAR")) {
                 PreparedStatement agregar;
                    try {
                        agregar = nConect.prepareStatement("INSERT INTO servicio (nombreServicio, categoria, precio)VALUES (?,?,?)");
                        agregar.setString(1, lblnombre.getText());
                        agregar.setString(2, combcat.getSelectedItem().toString());
                        agregar.setInt(3,  (Integer)jprecio.getValue());
                        agregar.executeUpdate();
                        System.out.println( "el precio guardado"+(Integer)jprecio.getValue());
                        new rojerusan.RSNotifyAnimated("¡AGREGADO!", "SERVICIO AGREGADO EXITOSAMENTE",
                        5, RSNotifyAnimated.PositionNotify.BottomRight,
                        RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                        lis.listar("");
                    } catch (SQLException ex) {

                    }
                    
                 
             }
            
             if (this.btnregistrar.getText().equals("GUARDAR")) {
                 try {
                     PreparedStatement modificar = nConect.prepareStatement("UPDATE servicio SET nombreServicio=?, categoria=?, precio=? WHERE id="+ Integer.parseInt(lblId.getText()));
                        modificar.setString(1, lblnombre.getText());
                        modificar.setString(2, combcat.getSelectedItem().toString());
                        modificar.setInt(3,  (Integer)jprecio.getValue());
                        modificar.executeUpdate();
                        System.out.println( "el precio guardado"+(Integer)jprecio.getValue());
                        new rojerusan.RSNotifyAnimated("¡MODIFICADO!", "SERVICIO MODIFICADO EXITOSAMENTE",
                        5, RSNotifyAnimated.PositionNotify.BottomRight,
                        RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                        lis.listar("");
                 } catch (SQLException ex) {
                     Logger.getLogger(insertarser.class.getName()).log(Level.SEVERE, null, ex);
                 }
              
             }

        }     
        

    }//GEN-LAST:event_btnregistrarActionPerformed

    private void jlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlimpiarActionPerformed
        this.lblnombre.requestFocus();
        this.lblnombre.setText("");
        this.combcat.setSelectedIndex(0);
        this.jprecio.setValue(0);
    }//GEN-LAST:event_jlimpiarActionPerformed

    private void lblnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblnombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblnombreKeyTyped


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertarser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertarser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertarser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertarser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                insertarser dialog = new insertarser();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox<String> combcat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToggleButton jlimpiar;
    private javax.swing.JSpinner jprecio;
    private javax.swing.JLabel lblCerrar1;
    public static javax.swing.JLabel lblId;
    public static javax.swing.JLabel lblId1;
    public static javax.swing.JTextField lblnombre;
    public static javax.swing.JLabel lbtitulo;
    // End of variables declaration//GEN-END:variables
 

}
