/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleados;

import Generarpdf.GenerarPDF;
import static Usuarios.Agregar.txfUsuario;
import conexion.Conectando;
import productos.*;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Label;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author  Lopez
 */
public class mostraremple extends javax.swing.JInternalFrame {
    Conectando con = new Conectando();
    Connection nConect;
    GenerarPDF pdf;
    /**
     * Creates new form Producto
     */
    public mostraremple() {
        initComponents();
        this.EMPLETAB.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.EMPLETAB.setDefaultRenderer(Object.class, new EstiloTablaRenderer(1));
        this.EMPLETAB.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.nConect = con.conect();
        fecha_sistema(fechacarta);
        listaemple.listar("");
        pdf = new GenerarPDF();
    }
 public static void verFila(){
        int aux = 0;
        while(aux <EMPLETAB.getRowCount()){
            if(!EMPLETAB.getValueAt(aux, 2).equals("1")){
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EMPLETAB = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        mostrarfotoempleado = new JPanelWebCam.JPanelWebCam();
        fecha = new javax.swing.JLabel();
        fechacarta = new javax.swing.JTextField();
        fecha2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        telefono = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO EMPLEADO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        EMPLETAB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EMPLETAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CUI", "NOMBRE", "CORREO", "FECHA DE NACIMIENTO", "TELEFONO", "ESTABLECIMIENTO", "HORAS", "ESTADO"
            }
        ));
        EMPLETAB.setGridColor(new java.awt.Color(204, 204, 204));
        EMPLETAB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMPLETABMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EMPLETAB);

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        lblCerrar.setBackground(new java.awt.Color(102, 0, 204));
        lblCerrar.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("x");
        lblCerrar.setOpaque(true);
        lblCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarMouseMoved(evt);
            }
        });
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLEADOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jButton2.setText("AGREGAR ESTABLECIMIENTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mostrarfotoempleado.setACTIVARCAMARA(false);
        mostrarfotoempleado.setEnabled(false);

        javax.swing.GroupLayout mostrarfotoempleadoLayout = new javax.swing.GroupLayout(mostrarfotoempleado);
        mostrarfotoempleado.setLayout(mostrarfotoempleadoLayout);
        mostrarfotoempleadoLayout.setHorizontalGroup(
            mostrarfotoempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        mostrarfotoempleadoLayout.setVerticalGroup(
            mostrarfotoempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        fecha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Fecha:");

        fechacarta.setBackground(new java.awt.Color(51, 51, 255));
        fechacarta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fechacarta.setForeground(new java.awt.Color(255, 255, 255));
        fechacarta.setBorder(null);
        fechacarta.setCaretColor(new java.awt.Color(255, 255, 255));
        fechacarta.setOpaque(false);
        fechacarta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechacartaKeyTyped(evt);
            }
        });

        fecha2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fecha2.setForeground(new java.awt.Color(255, 255, 255));
        fecha2.setText("Telefono:");

        jButton3.setText("GENERAR CARTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        telefono.setBackground(new java.awt.Color(51, 51, 255));
        telefono.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setBorder(null);
        telefono.setCaretColor(new java.awt.Color(255, 255, 255));
        telefono.setOpaque(false);
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(mostrarfotoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator1)
                                                    .addComponent(fechacarta, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(fecha2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                    .addComponent(jSeparator2))))
                                        .addGap(56, 56, 56))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jButton3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(64, 64, 64)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mostrarfotoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fechacarta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fecha)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fecha2)))
                        .addGap(35, 35, 35)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Agregarempleados ins = new Agregarempleados();
         ins.lblregistrar.setText("REGISTRAR");
        ins.btnregistrar.setText("REGISTRAR");
        ins.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed
    PreparedStatement buscar;
    public void consultar (int valor) throws SQLException, IOException{
       
        String nombre ="";
        buscar = nConect.prepareStatement("SELECT *FROM empleado WHERE CUI=?");
        buscar.setInt(1, valor);
        buscar.execute();

        ResultSet resultadosObtenidos=buscar.executeQuery();
        while(resultadosObtenidos.next()){
             nombre =  resultadosObtenidos.getString("nombre");
          
        }
        txfUsuario.setText(nombre);
       
        System.out.println(nombre);
    }
        
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (this.EMPLETAB.getRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "LA TABLA ESTÁ VACÍA");
        } else {
            if (this.EMPLETAB.getSelectedRowCount() < 1) {
                JOptionPane.showMessageDialog(null, "SELECCIONA UN REGISTRO");
            } else {

                int fila = this.EMPLETAB.getSelectedRow();

                Agregarempleados ins = new Agregarempleados();
                ins.txtcui1.setText(this.EMPLETAB.getValueAt(fila, 0).toString());
                ins.nombre1.setText(this.EMPLETAB.getValueAt(fila, 1).toString());
                ins.coreo.setText(this.EMPLETAB.getValueAt(fila, 2).toString());
                ins.fecha1.setText(this.EMPLETAB.getValueAt(fila, 3).toString());
                ins.telefono2.setText(this.EMPLETAB.getValueAt(fila, 4).toString());
                ins.combocompro.setSelectedIndex(setestado());
                ins.horaspresenciales1.setText(this.EMPLETAB.getValueAt(fila, 6).toString());
                
              //  ins.comboxesta.setSelectedIndex(setcomboesta());
                
        ImageIcon foto=null;
        InputStream is=null;
        String nombres;
        String fechai,fechafins;
        byte[] ima=null;
        //mostrar imagen
        try {
            String sql = "SELECT *FROM empleado where CUI="+ ins.txtcui1.getText();
            Statement st = nConect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                is = rs.getBinaryStream("cartal");
                ima = rs.getBytes("foto");
                fechai=rs.getString("fechainicio");
                fechafins=rs.getString("fechafin");
                BufferedImage bi = ImageIO.read(is);
                foto = new ImageIcon(bi);//convertir
                Image img = foto.getImage();
                Image ver = img.getScaledInstance(ins.lblfotoc1.getWidth(), ins.lblfotoc1.getHeight(), java.awt.Image.SCALE_DEFAULT);
                ImageIcon vers = new ImageIcon(ver);
                ins.fotografiacam.setImagen(ima);
                ins.lblfotoc1.setIcon(vers);
                ins.fechainicio.setText(fechai);
                ins.fechafin.setText(fechafins);
            }

        } catch (Exception e) {
        }
                
                ins.lblregistrar.setText("MODIFICAR");
                ins.btnregistrar.setEnabled(true);
                ins.btnregistrar.setText("GUARDAR");
                
                ins.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_btnModificarActionPerformed
public void consulta_mostrar_imagen(String x) throws SQLException, IOException {
        String nombres;
        ImageIcon foto=null;
        InputStream is=null;
        String fechai,fechafins;
        byte[] ima=null;
        //mostrar imagen
  
            String sql = "SELECT *FROM empleado where CUI="+x;
            Statement st = nConect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                ima = rs.getBytes("foto");
                fechai=rs.getString("fechainicio");
                fechafins=rs.getString("fechafin");
                mostrarfotoempleado.setImagen(ima);
              
                fechasi=fechai;
                fehcasfins=fechafins;
            }
    }
    private void lblCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseMoved
        lblCerrar.setBackground(Color.red);
    }//GEN-LAST:event_lblCerrarMouseMoved

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        lblCerrar.setBackground(new Color(102,0,204));
    }//GEN-LAST:event_lblCerrarMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         esta est = new esta();
        est.setVisible(true);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EMPLETABMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMPLETABMouseClicked
        int fila = this.EMPLETAB.getSelectedRow();
        String cui=this.EMPLETAB.getValueAt(fila, 0).toString();
        try {
            consulta_mostrar_imagen(cui);
        } catch (SQLException ex) {
            Logger.getLogger(mostraremple.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mostraremple.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EMPLETABMouseClicked
    
    
    public void horas_sistema(Label p){
            Calendar x = Calendar.getInstance();
            Calendar calendario = new GregorianCalendar();
            int hora, minutos, segundos;
                hora =calendario.get(Calendar.HOUR_OF_DAY);
                minutos = calendario.get(Calendar.MINUTE);
                segundos = calendario.get(Calendar.SECOND);
                String horas_s=hora + ":" + minutos + ":" + segundos;
                p.setText(horas_s);
    }
    
    public void fecha_sistema(JTextField x){
        Calendar fechas = Calendar.getInstance();    
        Calendar fecha = new GregorianCalendar();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);        
        String fecha_s= dia + " de " + (mes+1) + " de " + año;
        x.setText(fecha_s);
    }
    
    
    
    String fechasi,fehcasfins;
    private void fechacartaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechacartaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechacartaKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (this.EMPLETAB.getRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "LA TABLA ESTÁ VACÍA");
        } else {
            if (this.EMPLETAB.getSelectedRowCount() < 1) {
                JOptionPane.showMessageDialog(null, "SELECCIONA UN REGISTRO");
            } else {
                int fila = this.EMPLETAB.getSelectedRow();
                String nombreest=this.EMPLETAB.getValueAt(fila, 1).toString();
                String instituto=this.EMPLETAB.getValueAt(fila, 5).toString();
                String horas=this.EMPLETAB.getValueAt(fila, 6).toString();
                String dueño="Vivian Lizbeth López Barrios";		
                
                String fecha="Quetzaltenango,"+fechacarta.getText();
                String encabezado="Señores " +
                        "\n" +
                        instituto+
                        "\n" +
                       "Quetzaltenango";
                String cuerpo="Respetables señores:                                                " +
                    "\n" +
                    "Yo: "+dueño +" , me identifico con el Documento Personal "
                        + "de Identificación, Código único de Identificación número 1873 12559 0901.  "
                        + "Por medio de la presente me permito informarle que el/la estudiante "+nombreest
                        +" realizo "+horas+" horas de practica en el salón de mi propiedad "
                        + "denominada “ESTETICA LIZ”, ubicado en 2da. Calle 36-85 zona 8, Quetzaltenango. "
                        + "Iniciando el "+fechasi+" en horario de 7:00 am a 13:00 pm y de 13:30 pm a 18:00 pm,"
                        +" con media hora de almuerzo, culminando el "+fehcasfins+".                         " +"\n" +
                    
                    "Agradeciendo la atención a la presente, me despido de ustedes.                                                                                                                                         "+
                    "\n"+
                    "Atentamente:                                                " +
                    "\n";
                        String firma="F) _______________________________\n" +
                                "Vivian Lizbeth López Barrios\n" +
                                        "Cel. "+telefono.getText();
                pdf.generarpdf2(fecha, encabezado, cuerpo, "/Users/Lopez/Pictures/"+nombreest+".pdf", firma);             
            try {
                  String direcciones="/Users/Lopez/Pictures/"+nombreest+".pdf";
                  File paths = new File (direcciones);
                  Desktop.getDesktop().open(paths);
                }catch (IOException ex) {
                 ex.printStackTrace();
                }
            
            }

       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
      int limite = 8;
        char car = evt.getKeyChar();
        if (Character.isDigit(car) && car != KeyEvent.VK_SPACE) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
        if (telefono.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable EMPLETAB;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fecha2;
    public static javax.swing.JTextField fechacarta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCerrar;
    private JPanelWebCam.JPanelWebCam mostrarfotoempleado;
    public static javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
public int setestado() {
        int numero = 1;
        int fil = this.EMPLETAB.getSelectedRow();
        if(Integer.parseInt(this.EMPLETAB.getValueAt(fil, 7).toString()) == 0){
            return numero+1;
        }else
        return numero;
    }



}
